In [5]:
import torch
from torch import nn
import torch.nn.functional as F

In [6]:
input_dim = 4
inputs_list = [torch.randn(1, input_dim) for _ in range(5)]
print(inputs_list[0])
print(inputs_list[0].size())

tensor([[ 1.1749,  0.9119, -0.7646, -1.5695]])
torch.Size([1, 4])


In [7]:
inputs_list[0].view(1,1,-1)

tensor([[[ 1.1749,  0.9119, -0.7646, -1.5695]]])

In [14]:
X = torch.tensor([0,  8, 12,  0, 10])
print(X)

nn.Embedding(13, 6).forward(X)

tensor([ 0,  8, 12,  0, 10])


tensor([[ 0.0728, -1.9314, -0.6489,  0.0268, -0.5657,  0.1999],
        [ 1.3498, -0.5485, -0.1237,  0.2012,  0.9060, -1.2608],
        [-0.0460,  1.0053, -0.9752, -0.2309,  0.1135,  0.3091],
        [ 0.0728, -1.9314, -0.6489,  0.0268, -0.5657,  0.1999],
        [-0.4226, -0.2386,  0.4460, -0.7257,  0.9545,  1.4970]],
       grad_fn=<EmbeddingBackward>)